import express from 'express';
import { morganMiddleware } from './config/logger';
import { benefitsRouter } from './routes/benefits.routes';
import { categoriesRouter } from './routes/categories.routes';
import { notFound } from './middlewares/notFound';
import { errorHandler } from './middlewares/errorHandler';
const app = express();
app.use(express.json());
app.use(morganMiddleware);
app.get('/health', (_req, res) => { res.json({ status: 'ok', week: '06', project: 'mongodb-mongoose' }); });
app.use('/api/v1/benefits', benefitsRouter);
app.use('/api/v1/categories', categoriesRouter);
app.use(notFound);
app.use(errorHandler);
export default app;
